apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kind-workers
  namespace: metallb-system
spec:
  ipAddressPools:
    - kind
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: exp-traefik-worker
  - matchLabels:
      kubernetes.io/hostname: exp-traefik-worker2
