---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: traefik
    releaseName: traefik
    repo: https://traefik.github.io/charts
    version: 34.4.0
    includeCRDs: true
    valuesFile: traefik-metallb.values.yaml

resources:
  - traefik.serviceaccount.yaml
  - ingress.ns.yaml
  - traefik-static.configmap.yaml
