---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static
data:
  traefik.toml: |
    [core]
      defaultRuleSyntax = "v2"

    [log]
      level = "DEBUG"

    [ping]
      entryPoint = "traefik"

    [api]
      dashboard = true
      insecure = true

    [accessLog]
      bufferingSize = 0

    [entryPoints]

      [entryPoints.web]
        address = ":80"

      [entryPoints.traefik]
        address = ":8080"

      [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.http]
          [entryPoints.websecure.http.tls]

    [providers]
      providersThrottleDuration = "2s"

      [providers.kubernetescrd]
        allowCrossNamespace = false

      [providers.kubernetesingress]

      [providers.kubernetesGateway]
        experimentalChannel = true
        [providers.kubernetesGateway.statusAddress.service]
          name = "traefik"
          namespace = "ingress"
